import type {
  BillingClaimRow,
  BillingDenialRow,
  BillingPaymentRow,
  BillingWorkspaceRow,
} from "./BillingTypes";

export const BILLING_WORKSPACE_DEMO: BillingWorkspaceRow[] = [
  {
    id: "BW-1001",
    individualId: "IND-001",
    individualName: "John Doe",
    maNumber: "MA-001122",
    payer: "ODP",
    program: "Residential",
    serviceCode: "IN_HOME",
    serviceName: "In-Home Support",
    authorizationNumber: "AUTH-21001",
    authStatus: "VALID",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    visits: 5,
    units: 42,
    rate: 17.5,
    amount: 735,
    previouslyBilled: 0,
    remainingAuth: 118,
    claimNumber: null,
    readiness: "READY",
    visitQuality: "CLEAN",
    source: "VISITS",
  },
  {
    id: "BW-1002",
    individualId: "IND-002",
    individualName: "Emily Stone",
    maNumber: "MA-009911",
    payer: "CHC",
    program: "Community",
    serviceCode: "COMPANION",
    serviceName: "Companion",
    authorizationNumber: "AUTH-21002",
    authStatus: "VALID",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    visits: 4,
    units: 28,
    rate: 18,
    amount: 504,
    previouslyBilled: 0,
    remainingAuth: 72,
    claimNumber: null,
    readiness: "REVIEW",
    visitQuality: "MISSING_CLOCK",
    source: "VISITS",
  },
  {
    id: "BW-1003",
    individualId: "IND-003",
    individualName: "Kevin Brown",
    maNumber: "MA-887700",
    payer: "ODP",
    program: "Day Program",
    serviceCode: "COMMUNITY",
    serviceName: "Community Participation",
    authorizationNumber: null,
    authStatus: "MISSING",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    visits: 3,
    units: 18,
    rate: 19,
    amount: 342,
    previouslyBilled: 0,
    remainingAuth: null,
    claimNumber: null,
    readiness: "ERROR",
    visitQuality: "CLEAN",
    source: "VISITS",
  },
  {
    id: "BW-1004",
    individualId: "IND-004",
    individualName: "Michael Lee",
    maNumber: "MA-776611",
    payer: "PRIVATE",
    program: "Private Pay",
    serviceCode: "RESPITE",
    serviceName: "Respite",
    authorizationNumber: "AUTH-21004",
    authStatus: "NO_RATE",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    visits: 2,
    units: 12,
    rate: 0,
    amount: 0,
    previouslyBilled: 0,
    remainingAuth: 44,
    claimNumber: null,
    readiness: "HOLD",
    visitQuality: "MANUAL",
    source: "MANUAL",
  },
  {
    id: "BW-1005",
    individualId: "IND-005",
    individualName: "Sophia Carter",
    maNumber: "MA-557733",
    payer: "ODP",
    program: "Residential",
    serviceCode: "IN_HOME",
    serviceName: "In-Home Support",
    authorizationNumber: "AUTH-21005",
    authStatus: "VALID",
    periodFrom: "2026-02-22",
    periodTo: "2026-02-28",
    visits: 5,
    units: 40,
    rate: 17.5,
    amount: 700,
    previouslyBilled: 40,
    remainingAuth: 80,
    claimNumber: "CL-4102",
    readiness: "ALREADY_BILLED",
    visitQuality: "CLEAN",
    source: "IMPORT",
  },
];

export const BILLING_CLAIMS_DEMO: BillingClaimRow[] = [
  {
    id: "CL-4101",
    claimNumber: "CL-4101",
    billingDate: "2026-03-08",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    payer: "ODP",
    individualName: "John Doe",
    serviceSummary: "In-Home Support",
    units: 42,
    amount: 735,
    status: "DRAFT",
    submissionDate: null,
    paymentDate: null,
    balance: 735,
    source: "WORKSPACE",
  },
  {
    id: "CL-4102",
    claimNumber: "CL-4102",
    billingDate: "2026-03-01",
    periodFrom: "2026-02-22",
    periodTo: "2026-02-28",
    payer: "ODP",
    individualName: "Sophia Carter",
    serviceSummary: "In-Home Support",
    units: 40,
    amount: 700,
    status: "PAID",
    submissionDate: "2026-03-02",
    paymentDate: "2026-03-10",
    balance: 0,
    source: "IMPORT",
  },
  {
    id: "CL-4103",
    claimNumber: "CL-4103",
    billingDate: "2026-03-08",
    periodFrom: "2026-03-01",
    periodTo: "2026-03-07",
    payer: "CHC",
    individualName: "Emily Stone",
    serviceSummary: "Companion",
    units: 28,
    amount: 504,
    status: "DENIED",
    submissionDate: "2026-03-09",
    paymentDate: null,
    balance: 504,
    source: "WORKSPACE",
  },
];

export const BILLING_DENIALS_DEMO: BillingDenialRow[] = [
  {
    id: "DN-1001",
    claimNumber: "CL-4103",
    individualName: "Emily Stone",
    serviceCode: "COMPANION",
    deniedUnits: 8,
    deniedAmount: 144,
    denialCode: "EVV-01",
    denialReason: "Missing EVV confirmation for one visit.",
    rootCause: "EVV",
    assignedTo: "Office Admin",
    status: "OPEN",
    linkedAuth: "AUTH-21002",
    linkedVisit: "VIS-90211",
  },
  {
    id: "DN-1002",
    claimNumber: "CL-4098",
    individualName: "Kevin Brown",
    serviceCode: "COMMUNITY",
    deniedUnits: 6,
    deniedAmount: 114,
    denialCode: "AUTH-03",
    denialReason: "Authorization missing for billed dates.",
    rootCause: "AUTH",
    assignedTo: "Billing Lead",
    status: "IN_PROGRESS",
    linkedAuth: null,
    linkedVisit: "VIS-90110",
  },
];

export const BILLING_PAYMENTS_DEMO: BillingPaymentRow[] = [
  {
    id: "PM-2001",
    paymentNumber: "PM-2001",
    receivedDate: "2026-03-10",
    payer: "ODP",
    amount: 700,
    applied: 700,
    unapplied: 0,
    claimsCount: 1,
    status: "POSTED",
    referenceNo: "EFT-88441",
  },
  {
    id: "PM-2002",
    paymentNumber: "PM-2002",
    receivedDate: "2026-03-12",
    payer: "CHC",
    amount: 504,
    applied: 360,
    unapplied: 144,
    claimsCount: 1,
    status: "PARTIAL",
    referenceNo: "CHK-77210",
  },
];